name: Update Gantt Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-gantt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch Gantt data from Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: |
          python fetch_gantt.py

      - name: Commit updated data
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add gantt_data.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Gantt chart data from Notion [automated]"
            git push
          fi

